services:
  mandamel-db:
    image: mysql:latest
    container_name: mandamel-db
    restart: always
    environment:
      MYSQL_DATABASE: mandamel
      MYSQL_USER: mandamel
      MYSQL_PASSWORD: mandamel
      MYSQL_ROOT_PASSWORD: mandamel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql

  php-apache:
    build:
      context: ./backend/.devcontainer
      dockerfile: Dockerfile
    container_name: mandamel-app
    ports:
      - "5000:80"
      - "9003:9003"
    volumes:
      - ./backend:/var/www/html
    # For production (or security testing)
    # volumes:
      # - ./backend/public:/var/www/html
    depends_on:
      - mandamel-db
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mandamel-pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mandamel-db
      PMA_USER: mandamel
      PMA_PASSWORD: mandamel
    depends_on:
      - mandamel-db

  frontend:
    build:
      context: ./frontend/.devcontainer
      dockerfile: Dockerfile
    container_name: mandamel-frontend
    ports:
      - "3000:80"
      - "9004:9004" # http://localhost:3000
    volumes:
    - ./frontend:/var/www/html    
    depends_on:
      - php-apache
    networks:
      - mandamel    

volumes:
  db_data:

networks:
  mandamel:  