services:
  mandamel-db:
    image: mysql:latest
    container_name: mandamel-db
    restart: always
    environment:
      MYSQL_DATABASE: mandamel
      MYSQL_USER: mandamel
      MYSQL_PASSWORD: mandamel
      MYSQL_ROOT_PASSWORD: mandamel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    container_name: mandamel-app
    depends_on:
      - mandamel-db
    ports:
      - "5000:80"
    volumes:
      - ./website:/var/www/html

volumes:
  db_data:
